#!/bin/sh

export WINEPREFIX=/home/ninez/Winebox/winebox-master
export WINEPATH="/usr/lib"
export NTDLL_RT_POLICY="TS"
export STAGING_WRITECOPY=0
export WINEFSYNC=0
export WINEESYNC=0
export WINE_LOGICAL_CPUS_AS_CORES=1

exec wine '/home/ninez/Winebox/winebox-master/drive_c/Program Files/Native Instruments/Native Access/Native Access.exe' 
